nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.9.1.cjs

# These deps were added in the patch but yarn does not install them for some reason
packageExtensions:
  backfill-cache@*:
    dependencies:
      "@aws-sdk/client-s3": "^3.804.0"
      "@aws-sdk/lib-storage": "^3.804.0"
  backfill-config@*:
    dependencies:
      "@aws-sdk/client-s3": "^3.804.0"

